### ISSUE TITLE
Add this module to Ansible

### ISSUE THREAD

**Issue by equelin** [equelin/ansible-win_pester#3]
Hello @jborean93,

I don't want to pollute the Ansible repo so I'm asking my question here. Do you think that this module can be added directly in Ansible ?

The purpose of the module is to be able to run Pester tests on Windows hosts with Ansible.

Regards,

**Comment by jborean93** [comment]
Feel free to open a PR or talk about it in the next working group. You can always host the module in Ansible Galaxy in an empty shell role. I like the documentation though and seems like you've done some work here.

**Comment by equelin** [comment]
Thanks for the feedback @jborean93. I will try to open a PR.
